groups:
- name: kubernetes.rules
  rules:
  - alert: KubernetesPodCrashLooping
    expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Kubernetes pod is crash looping"
      description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"

  - alert: KubernetesNodeNotReady
    expr: kube_node_status_condition{condition="Ready",status="true"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Kubernetes Node not ready"
      description: "Node {{ $labels.node }} has been not ready for more than 5 minutes"

  - alert: KubernetesPodNotReady
    expr: kube_pod_status_phase{phase=~"Pending|Unknown"} > 0
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "Kubernetes pod not ready"
      description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-ready state for longer than 15 minutes."

- name: loki.rules
  rules:
  - alert: LokiHighErrorRate
    expr: sum(rate(loki_request_duration_seconds_count{status_code=~"5.."}[5m])) > 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Loki high error rate"
      description: "Loki is experiencing {{ $value }} errors per second"

- name: system.rules
  rules:
  - alert: HighMemoryUsage
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory usage is above 80% on {{ $labels.instance }}"